.PHONY: up down build migrate seed test logs setup shell-db

up:
up:
	# Docker commands removed

down:
	# Docker commands removed

build:
	# Docker commands removed

migrate:
	# Docker commands removed

seed:
	# Docker commands removed

logs:
	# Docker commands removed

test:
	# Docker commands removed

setup: build up
	@echo "Waiting for DB to be ready..."
	@sleep 5
	# Docker commands removed

shell-db:
	# Docker commands removed
