from pydantic import BaseModel, Field
import uuid
from typing import List, Dict, Any, Optional

class QuoteScore(BaseModel):
    quote_id: uuid.UUID = Field(..., description="ID of the supplier quote")
    supplier_id: uuid.UUID = Field(..., description="ID of the supplier")
    score: float = Field(..., description="Deterministic score computed for the quote")
    criteria: Dict[str, Any] = Field(..., description="Breakdown of criteria evaluations")

class ComparisonResponse(BaseModel):
    rfq_id: uuid.UUID = Field(..., description="RFQ identifier")
    ranked_quotes: List[QuoteScore] = Field(..., description="Quotes sorted by score descending")
    best_match: Optional[QuoteScore] = Field(None, description="Top-ranked quote, if any")
    explanation: str = Field(..., description="Human‑readable justification generated by LLM")
    recommendation_id: Optional[str] = Field(None, description="ID of the persisted ProcurementRecommendation")
